// <auto-generated />
using System;
using CabinetVeterinar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CabinetVeterinar.Migrations
{
    [DbContext(typeof(CabinetVeterinarContext))]
    [Migration("20231114171243_FinalMigrationForCategory")]
    partial class FinalMigrationForCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CabinetVeterinar.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("CabinetVeterinar.Models.Cabinet", b =>
                {
                    b.Property<int>("CabinetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CabinetId"), 1L, 1);

                    b.Property<int?>("AnimalID")
                        .HasColumnType("int");

                    b.Property<string>("CabinetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VetID")
                        .HasColumnType("int");

                    b.HasKey("CabinetId");

                    b.HasIndex("AnimalID");

                    b.HasIndex("VetID");

                    b.ToTable("Cabinet");
                });

            modelBuilder.Entity("CabinetVeterinar.Models.CabinetTypes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CabinetID")
                        .HasColumnType("int");

                    b.Property<int>("EmergencyTypeId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CabinetID");

                    b.HasIndex("EmergencyTypeId");

                    b.ToTable("CabinetTypes");
                });

            modelBuilder.Entity("CabinetVeterinar.Models.EmergencyType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("TypeOfUrgency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EmergencyType");
                });

            modelBuilder.Entity("CabinetVeterinar.Models.Vet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vet");
                });

            modelBuilder.Entity("CabinetVeterinar.Models.Cabinet", b =>
                {
                    b.HasOne("CabinetVeterinar.Models.Animal", "Animal")
                        .WithMany("Cabinets")
                        .HasForeignKey("AnimalID");

                    b.HasOne("CabinetVeterinar.Models.Vet", "Vet")
                        .WithMany("Cabinets")
                        .HasForeignKey("VetID");

                    b.Navigation("Animal");

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("CabinetVeterinar.Models.CabinetTypes", b =>
                {
                    b.HasOne("CabinetVeterinar.Models.Cabinet", "Cabinet")
                        .WithMany("CabinetTypes")
                        .HasForeignKey("CabinetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CabinetVeterinar.Models.EmergencyType", "EmergencyType")
                        .WithMany("CabinetTypes")
                        .HasForeignKey("EmergencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("EmergencyType");
                });

            modelBuilder.Entity("CabinetVeterinar.Models.Animal", b =>
                {
                    b.Navigation("Cabinets");
                });

            modelBuilder.Entity("CabinetVeterinar.Models.Cabinet", b =>
                {
                    b.Navigation("CabinetTypes");
                });

            modelBuilder.Entity("CabinetVeterinar.Models.EmergencyType", b =>
                {
                    b.Navigation("CabinetTypes");
                });

            modelBuilder.Entity("CabinetVeterinar.Models.Vet", b =>
                {
                    b.Navigation("Cabinets");
                });
#pragma warning restore 612, 618
        }
    }
}
